### ISSUE TITLE
Ruby 1.9 Hash Sorting?

### ISSUE THREAD

**Issue by pwood** [livingsocial/ankusa#7]
Hey,

Using ankusa-0.0.13, in RVM with Ruby 1.9.3.

I found I needed to alter lib/ankusa/naive_bayes.rb in order to cope with values returned by log_likelihoods which were Infinity.

When I had categories with no matches at all they were being suggested instead of the correct one.

Replacing:
      log_likelihoods(text, classes).sort_by { |c| -c[1] }.first.first

With:
      log_likelihoods(text, classes).sort_by { |c| (c[1] != INFTY)? (c[1] \* -1) : c[1] }.first.first

I'm not sure if you'd never come across this situation, or if this is a change of behaviour in sorting with the Infinity values.

Fix it for me anyway.

Cheers,

P.

**Comment by bmuller** [comment]
Thanks - fixed in 7070bb3 and version 0.0.14
